resolver: lts-14.27

extra-deps:
  - git: https://github.com/juhp/hsbugzilla.git
    commit: ae1fa7be0e3480c6979fc04f232cc09c16e4cb7d
  - git: https://github.com/juhp/fedora-dists.git
    commit: 8f8311921d4c9f4ce763c2c146af56f136bd0e7e
  - config-ini-0.2.4.0
