resolver: lts-14.26

extra-deps:
  - git: https://github.com/juhp/hsbugzilla.git
    commit: e3b424e2f562cebc94bfdf2cc7b466108be15b7a
  - git: https://github.com/juhp/fedora-dists.git
    commit: 78643db27bb9aca9b2f929db4c5c35a80e18888b
